# isonim-docs — task entry points (mirrors ../isonim/Justfile's style).
#
# Every recipe assumes the IsoNim dev shell is active (Nim, nimble, just
# all come from there -- there is no global nim). From a clean checkout:
#   nix develop ../isonim -c just ci-docs

# Run the M0 + M1 + M2 suites on the C target.
docs-test-c:
    nim c -r tests/docs/test_bootstrap_vm.nim
    nim c -r tests/docs/test_bootstrap_mock.nim
    nim c -r tests/docs/test_bootstrap_renderroute.nim
    nim c -r tests/docs/test_routes_vm.nim
    nim c -r tests/docs/test_routes_mock.nim
    nim c -r tests/docs/test_routes_renderroute.nim
    nim c -r tests/docs/test_routes_logging.nim
    nim c -r tests/docs/test_markdown_vm.nim
    nim c -r tests/docs/test_markdown_anchor_ids.nim
    nim c -r tests/docs/test_markdown_mock.nim
    nim c -r tests/docs/test_markdown_tabs.nim
    nim c -r tests/docs/test_content_components.nim
    nim c -r tests/docs/test_syntax_highlight.nim
    nim c -r tests/docs/test_code_copy_mock.nim
    nim c -r tests/docs/test_markdown_renderroute.nim
    nim c -r tests/docs/test_openapi_ingest.nim
    nim c -r tests/docs/test_api_reference_renderroute.nim
    nim c -r tests/docs/test_nimdoc_parse.nim
    nim c -r tests/docs/test_symbol_reference_renderroute.nim
    nim c -r tests/docs/test_content_loader.nim
    nim c -r tests/docs/test_manifest_from_content.nim
    nim c -r tests/docs/test_manifest_from_content_renderroute.nim
    nim c -r tests/docs/test_autoroute_renderroute.nim
    nim c -r tests/docs/test_navigation_vm.nim
    nim c -r tests/docs/test_navigation_mock.nim
    nim c -r tests/docs/test_navigation_renderroute.nim
    nim c -r tests/docs/test_nav_tree_deep.nim
    nim c -r tests/docs/test_references_vm.nim
    nim c -r tests/docs/test_references_renderroute.nim
    nim c -r tests/docs/test_redirects_vm.nim
    nim c -r tests/docs/test_redirects_renderroute.nim
    nim c -r tests/docs/test_docs_graph_integration.nim
    nim c -r tests/docs/test_docs_graph_integration_renderroute.nim
    nim c -r tests/docs/test_authoring_fixtures.nim
    nim c -r tests/docs/test_authoring_fixtures_renderroute.nim
    nim c -r tests/docs/test_search_vm.nim
    nim c -r tests/docs/test_search_mock.nim
    nim c -r tests/docs/test_search_renderroute.nim
    nim c -r tests/docs/test_search_index_artifact.nim
    nim c -r tests/docs/test_theme_vm.nim
    nim c -r tests/docs/test_theme_mock.nim
    nim c -r tests/docs/test_asset_pipeline.nim
    nim c -r tests/docs/test_completeness_vm.nim
    nim c -r tests/docs/test_framework_is_content_agnostic.nim
    nim c -r tests/docs/test_router_vm.nim
    nim c -r tests/docs/test_seo_head.nim
    nim c -r tests/docs/test_component_error_boundary.nim
    nim c -r tests/docs/test_component_extract.nim
    nim c -r tests/docs/test_error_fallback_renderroute.nim
    nim c -r tests/docs/test_tutorial_vm.nim
    nim c -r tests/docs/test_versioning_routes.nim
    nim c -r tests/docs/test_versioning_renderroute.nim
    nim c -r tests/docs/test_i18n.nim
    nim c -r tests/docs/test_i18n_renderroute.nim
    nim c -r tests/docs/test_plugin_hooks.nim
    nim c -r tests/docs/test_dev_server.nim
    nim c -r tests/docs/test_cli.nim
    nim c -r tests/docs/test_nginx_target.nim
    nim c -r tests/docs/test_server_search.nim
    nim c -r tests/docs/test_csp_analytics.nim
    nim c -r tests/docs/test_optional_config_hooks_are_noops_when_unset.nim
    nim c -r tests/docs/test_chrome_hooks_noop_when_unset.nim
    nim c -r tests/tokens/test_dtcg_resolver.nim
    nim c -r tests/tokens/test_token_css_emitter.nim

# isonim's `ui` DSL unconditionally imports `isonim/dsl/tailwind`, which
# under the JS target hard-requires ../isonim/build/tailwind-styles.json
# at compile time (the C target tolerates it being absent). That file is
# generated by isonim's own Justfile, from the real Tailwind CLI over
# isonim's real source -- not something isonim-docs vendors or fakes.
# A clean checkout has no `../isonim/build/`, so every JS-target compile
# depends on this first.
tailwind-bootstrap:
    just --justfile ../isonim/Justfile --working-directory ../isonim build-tailwind

# Run the M0 + M1 + M2 suites on the JS target.
docs-test-js: tailwind-bootstrap
    nim js -r tests/docs/test_bootstrap_vm.nim
    nim js -r tests/docs/test_bootstrap_mock.nim
    nim js -r tests/docs/test_bootstrap_browser_mount.nim
    nim js -r tests/docs/test_routes_vm.nim
    nim js -r tests/docs/test_routes_mock.nim
    nim js -r tests/docs/test_routes_browser_mount.nim
    nim js -r tests/docs/test_manifest_from_content.nim
    nim js -r tests/docs/test_markdown_vm.nim
    nim js -r tests/docs/test_markdown_anchor_ids.nim
    nim js -r tests/docs/test_markdown_mock.nim
    nim js -r tests/docs/test_markdown_tabs.nim
    nim js -r tests/docs/test_content_components.nim
    nim js -r tests/docs/test_syntax_highlight.nim
    nim js -r tests/docs/test_code_copy_mock.nim
    nim js -r tests/docs/test_markdown_browser_mount.nim
    nim js -r tests/docs/test_openapi_ingest.nim
    nim js -r tests/docs/test_nimdoc_parse.nim
    nim js -r tests/docs/test_code_copy_browser_mount.nim
    nim js -r tests/docs/test_navigation_vm.nim
    nim js -r tests/docs/test_navigation_mock.nim
    nim js -r tests/docs/test_nav_tree_deep.nim
    nim js -r tests/docs/test_references_vm.nim
    nim js -r tests/docs/test_redirects_vm.nim
    nim js -r tests/docs/test_docs_graph_integration.nim
    nim js -r tests/docs/test_authoring_fixtures.nim
    nim js -r tests/docs/test_search_vm.nim
    nim js -r tests/docs/test_search_mock.nim
    nim js -r tests/docs/test_search_browser_mount.nim
    nim js -r tests/docs/test_search_shortcuts_browser_mount.nim
    nim js -r tests/docs/test_theme_vm.nim
    nim js -r tests/docs/test_theme_mock.nim
    nim js -r tests/docs/test_completeness_vm.nim
    nim js -r tests/docs/test_framework_is_content_agnostic.nim
    nim js -r tests/docs/test_hydration_browser_mount.nim
    nim js -r tests/docs/test_router_vm.nim
    nim js -r tests/docs/test_soft_nav_browser_mount.nim
    nim js -r tests/docs/test_nav_drawer_browser_mount.nim
    nim js -r tests/docs/test_seo_head.nim
    nim js -r tests/docs/test_component_error_boundary.nim
    nim js -r tests/docs/test_component_extract.nim
    nim js -r tests/docs/test_component_embed_browser_mount.nim
    nim js -r tests/docs/test_tutorial_vm.nim
    nim js -r tests/docs/test_versioning_routes.nim
    nim js -r tests/docs/test_i18n.nim
    nim js -r tests/docs/test_plugin_hooks.nim
    nim js -r tests/docs/test_server_search.nim
    nim js -r tests/docs/test_csp_analytics.nim

# Run the full dual-target docs test matrix.
docs-test: docs-test-c docs-test-js

# Fast compile-only pass over both Layer-4 shell entry points (SSR +
# browser mount) on their real targets, against the real `content/`
# dir. Doesn't run anything -- it exists to catch "the proof route
# stopped compiling for real" regressions cheaply, without paying for
# the full dual-target test matrix on every save. `check_links` is the
# one exception: it's run for real (M3 deliverable 2's build gate), so a
# broken internal reference in the real content corpus fails this step
# with the offending file:line rather than shipping a dead link.
docs-smoke: tailwind-bootstrap
    nim c --compileOnly --hints:off src/ssr.nim
    nim js --compileOnly --hints:off src/main_web.nim
    nim c --compileOnly --hints:off src/cli.nim
    nim c -r --hints:off src/check_links.nim

# The single entry point a clean checkout uses: full test matrix plus
# the compile smoke, so a green `ci-docs` means both "the suites pass"
# and "the real shells still compile against real content".
ci-docs: docs-test docs-smoke

# --- M4 deliverable 5: production build (SSG) ---
# Statically generate the whole site into ./public via the shared renderRoute
# SSR path (one codebase -> SSG here, SSR via ssr.nim, SPA via main_web.nim).
docs-build: tailwind-bootstrap
    nim c -r --hints:off -o:build/build_site src/build_site.nim

# --- M11 deliverable 2: dev server ---
# Live-reloading dev server (HTTP + file watcher + websocket live-reload +
# a browser error overlay on build failure) over the checked-in mini-site
# fixture. A real consumer's dev entry constructs a DevServer over its own
# content dir; the CLI's `dev` subcommand (M11 deliverable 3) wraps this.
docs-dev:
    nim c -r --hints:off src/dev_server.nim

# --- M11 deliverable 3: CLI toolchain ---
# The `isonim-docs` binary: init/dev/build/serve subcommands, colored
# output, and flag/.env config overrides. A thin front-end over the same
# buildSite (SSG) and DevServer entry points the other recipes use.
docs-cli *ARGS:
    nim c --hints:off -o:build/isonim-docs src/cli.nim
    ./build/isonim-docs {{ARGS}}

# --- M4 deliverable 4: release gate ---
# A releasable candidate must pass every check with no hidden manual steps:
# full dual-target test suite (clean build + no broken links + search coverage
# + examples compile + SSR render + JS mount parity), the compile smoke, and a
# clean production build.
release-gate: docs-test docs-smoke docs-build
    @echo "RELEASE GATE PASSED: tests green (C+JS), smoke ok, site built to ./public"
